export const mockRoom = [
  {
    id: 1,
    room: "101",
    totalBeds: 4,
    availableBeds: 1,
    occupiedBeds: 3,
    status: "Almost Full",
  },
  {
    id: 2,
    room: "102",
    totalBeds: 3,
    availableBeds: 0,
    occupiedBeds: 3,
    status: "Full",
  },
  {
    id: 3,
    room: "103",
    totalBeds: 5,
    availableBeds: 2,
    occupiedBeds: 3,
    status: "Available",
  },
  {
    id: 4,
    room: "104",
    totalBeds: 2,
    availableBeds: 2,
    occupiedBeds: 0,
    status: "Empty",
  },
  {
    id: 5,
    room: "105",
    totalBeds: 4,
    availableBeds: 0,
    occupiedBeds: 4,
    status: "Full",
  },
  {
    id: 6,
    room: "106",
    totalBeds: 6,
    availableBeds: 3,
    occupiedBeds: 3,
    status: "Available",
  },
  {
    id: 7,
    room: "107",
    totalBeds: 3,
    availableBeds: 1,
    occupiedBeds: 2,
    status: "Almost Full",
  },
  {
    id: 8,
    room: "108",
    totalBeds: 5,
    availableBeds: 5,
    occupiedBeds: 0,
    status: "Empty",
  },
  {
    id: 9,
    room: "109",
    totalBeds: 4,
    availableBeds: 2,
    occupiedBeds: 2,
    status: "Available",
  },
  {
    id: 10,
    room: "110",
    totalBeds: 2,
    availableBeds: 0,
    occupiedBeds: 2,
    status: "Full",
  },
];
